version: '3.8'
services:
  db:
    container_name: db_postgres
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]

  api:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    container_name: migrations
    build:
      context: .
    environment:
    - DJANGO_SUPERUSER_USERNAME=admin
    - DJANGO_SUPERUSER_PASSWORD=admin
    - DJANGO_SUPERUSER_EMAIL=admin@example.com
    command: >
      bash -c "python manage.py migrate && python manage.py createsuperuser --no-input"
    depends_on:
      db:
        condition: service_healthy
